#!/bin/bash
export DJANGO_SETTINGS_MODULE="drams.local-settings"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SCRC_HOME="$(dirname "${DIR}")"
nohup "$SCRC_HOME"/venv/bin/python "$SCRC_HOME"/manage.py runserver > $SCRC_HOME/output.log &

{ bash -c 'until curl http://localhost:8000; do sleep 0.5; done'; } > /dev/null 2>&1
retVal=$?
if [ $retVal -ne 0 ]; then
    echo Error starting local registry
else
    echo Local registry now accepting connections on http://localhost:8000
fi

python3 manage.py get_token > "$SCRC_HOME"/token
chmod 600 "$SCRC_HOME"/token
echo An access token for the REST API is available in the file "$SCRC_HOME"/token

unset DJANGO_SETTINGS_MODULE
