name: FAIR Data Registry
on: [push]
jobs:
  test:
    name: Test ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install graphviz on ubuntu
        run:  |
              if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo apt-get install graphviz
              else
                  brew install graphviz
              fi
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "local-requirements.txt"
      - name: Run Tests
        run: python manage.py test --settings drams.test-settings
  deploy-local-registry:
    name: Deploy local registry on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.7"]
    env:
      REGISTRY_PORT: 8001
      INSTALL_DIR: fair
    steps:
      - uses: actions/setup-python@v2
      - name: Deploy registry
        run: curl -fsSL https://raw.githubusercontent.com/FAIRDataPipeline/data-registry/${GITHUB_REF/refs\/heads\//}/static/localregistry.sh | bash -s -- -d $INSTALL_DIR -b ${GITHUB_REF/refs\/heads\//}
      - name: Start registry
        run: $INSTALL_DIR/registry/scripts/start_fair_registry -p $REGISTRY_PORT
      - name: Test registry
        run: curl http://localhost:$REGISTRY_PORT/api/
